export const GET_PIZZAS = 'GET_PIZZAS';
export const GET_DOUGH_TYPES = 'GET_DOUGH_TYPES';
export const GET_PIZZA_SIZES = 'GET_PIZZA_SIZES';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_SORT_CRITERIA = 'GET_SORT_CRITERIA';

export const SELECT_OPTIONS = 'SELECT_OPTIONS';

export const CHANGE_CATEGORY = 'CHANGE_CATEGORY';

export const CHANGE_SORT_CRITERION = 'CHANGE_SORT_CRITERION';

export const ADD_PIZZA_TO_BASKET = 'ADD_PIZZA_TO_BASKET';

export const CALCULATE_TOTAL_DATA = 'CALCULATE_TOTAL_DATA';

export const CLEAR_SELECTED_OPTIONS = 'CLEAR_SELECTED_OPTIONS';
